
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - npm test
deploy:
  # deploy develop to the dev environment
  provider: script
  script: 
    - chmod ugo+x ./deploy.sh
    - ./deploy.sh
    on:
      branch: dev
