language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script: 
  - npm run test
deploy:
  # deploy dev to the staging environment
  - provider: script
    script: bash ./deploy.sh
    skip_cleanup: true # do not delete the built assets
    stripeSecretKey: 
      secure: "g4fmuYHFR6VCn3cV186GCCNbfC//gjKedCmAFpyiiv5ABIrdNsmmS1SKPhN6ntPej1+/MBTf7a2jQMPNojg4Qh/fJ/X2T+HDSarAabduuU+6qrhmTMVlYSYhKJ6j5jfzEp0X0N9lBs+POSSnihHTMQq6/1bSdM1T/pPL9QR4v3TruLC8lvPcjcmx9pDwlzqcgbGQsJNHTyWddxAR0BzwOMk3+5+/7joOzA4zgTlQyImo3i0j+BZovTkZtODKy/HfDfu2cUOPZWTlPjSvwPycM+/Ripf4B8wDWMXloAiRTjow03gATW+Se3KSZ1sFC6wsrlmNCoBRLuZ8QWbppTNLPE9yIpyOkXq3icrT1/UcO9zKAPkPSYDiF2QxZkhGj5dpGqRsAxwFQk8N7ZWPNcbns9IpZNY9VuD2W+r56Wc088l/Wxi7UBZXdFBfIO4t40OvP4+lQ3LYKcuGbTFk/dcPZw7DY3tW+wikcRqakpwBV4Ir9/HknBKR4PnaADgAvpS4WGk0ZxlIG66Yw4IMozorQZga/+2CWebwhFqbAbyFxEjuriPy6CPi7q4CimLF4Akak+o+x4k6dXzIN2KhyfIkT8HTpf2JAbsEbFgacvkAWdl5s6ePhz5/Emlctkg5cSMBap9cIKJCXtxa3Hc0vdsrjo+eseZFjiS3GvTVpLEc+X0="
    on:
      branch: dev
  # deploy master to production
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: bash ./deploy.sh
    on:
      branch: master