language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: dev
  # deploy master to production
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master