
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
deploy:
  # deploy develop to the dev environment
  - provider: script
    script: 
        - npm install -g serverless
        - sls deploy
    on:
      branch: dev
